### ISSUE TITLE
Fix Labels

### ISSUE THREAD

**Issue by paixlukee** [DiscordBotIndex/Feedback#2]
**Type** Suggestion

**Description** (This if for this repo) I would like the `bug` label to be black (`#000000`), and I would like all of the labels to be lowercase. This will make me/the others happy.

**Links/images** None

**Comment by SamuraiStacks** [comment]
Why exactly do the labels have to be lowercase?

**Comment by ohlookitsderpy** [comment]
^^

**Comment by paixlukee** [comment]
Because it soothes your users

**Comment by paixlukee** [comment]
:cry:

**Comment by ohlookitsderpy** [comment]
@SamuraiStacks i'm lazy af you do it pls

**Comment by SamuraiStacks** [comment]
Not really needed but I'll do it anyway
