### ISSUE TITLE
t> shows up as t>GT;

### ISSUE THREAD

**Issue by vilP1l** [DiscordBotIndex/Feedback#7]
**Issue**

Description - t> displays as T & GT;

Expected Behaviour - t> shows up as t>

Steps to reproduce - 
* click [here](https://discordbotindex.com/bot/509165356791889931)

Platform - macOS 10.14 - Chrome 70.0.3538.102 (Official Build) (64-bit)

**Comment by SamuraiStacks** [comment]
t> displays as t> but its supposed to be t>?

**Comment by SamuraiStacks** [comment]
oh github does that

**Comment by SamuraiStacks** [comment]
t & g t ; without spaces

**Comment by SamuraiStacks** [comment]
and yea it will be fixed
